"""add_template_marketplace_tables

Revision ID: 08278ff856b1
Revises: 20fd9cfd6dc9
Create Date: 2026-03-20 14:48:13.099894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08278ff856b1'
down_revision: Union[str, None] = '20fd9cfd6dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('writer_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_krw', sa.Integer(), nullable=False),
    sa.Column('future_year', sa.Integer(), nullable=False),
    sa.Column('preview_headline', sa.String(length=300), nullable=True),
    sa.Column('preview_lead', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue_krw', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_series_status'), 'template_series', ['status'], unique=False)
    op.create_index(op.f('ix_template_series_writer_id'), 'template_series', ['writer_id'], unique=False)
    op.create_table('template_episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('headline_template', sa.String(length=300), nullable=False),
    sa.Column('subhead_template', sa.String(length=300), nullable=False),
    sa.Column('lead_paragraph_template', sa.Text(), nullable=False),
    sa.Column('body_content_template', sa.Text(), nullable=False),
    sa.Column('sidebar_template', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_episodes_template_id'), 'template_episodes', ['template_id'], unique=False)
    op.create_table('template_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('slot_values', sa.JSON(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('amount_krw', sa.Integer(), nullable=False),
    sa.Column('merchant_uid', sa.String(length=100), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['template_series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_uid')
    )
    op.create_index(op.f('ix_template_purchases_buyer_id'), 'template_purchases', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_template_purchases_template_id'), 'template_purchases', ['template_id'], unique=False)
    op.create_table('template_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('slot_key', sa.String(length=50), nullable=False),
    sa.Column('slot_label', sa.String(length=100), nullable=False),
    sa.Column('slot_hint', sa.String(length=200), nullable=True),
    sa.Column('slot_category', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_slots_template_id'), 'template_slots', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_slots_template_id'), table_name='template_slots')
    op.drop_table('template_slots')
    op.drop_index(op.f('ix_template_purchases_template_id'), table_name='template_purchases')
    op.drop_index(op.f('ix_template_purchases_buyer_id'), table_name='template_purchases')
    op.drop_table('template_purchases')
    op.drop_index(op.f('ix_template_episodes_template_id'), table_name='template_episodes')
    op.drop_table('template_episodes')
    op.drop_index(op.f('ix_template_series_writer_id'), table_name='template_series')
    op.drop_index(op.f('ix_template_series_status'), table_name='template_series')
    op.drop_table('template_series')
    # ### end Alembic commands ###
