"""add_template_marketplace

Revision ID: 20fd9cfd6dc9
Revises: 8fcc12892840
Create Date: 2026-03-20 14:45:43.006734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20fd9cfd6dc9'
down_revision: Union[str, None] = '8fcc12892840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_items_collection_name'), table_name='vector_items')
    op.drop_index(op.f('ix_vector_items_external_id'), table_name='vector_items')
    op.drop_table('vector_items')
    op.alter_column('newspapers', 'sns_copy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newspapers', 'sns_copy',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_table('vector_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_items_pkey'))
    )
    op.create_index(op.f('ix_vector_items_external_id'), 'vector_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_vector_items_collection_name'), 'vector_items', ['collection_name'], unique=False)
    # ### end Alembic commands ###
