"""add_hybrid_auth_schema_v2

Revision ID: 2c4b6dac4c06
Revises: 001
Create Date: 2026-02-18 00:33:22.764398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4b6dac4c06'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_id'), 'refresh_tokens', ['token_id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('idx_agent_logs_agent_type'), table_name='agent_logs')
    op.drop_index(op.f('idx_agent_logs_created_at'), table_name='agent_logs')
    op.drop_index(op.f('idx_agent_logs_order_id'), table_name='agent_logs')
    op.create_index(op.f('ix_agent_logs_agent_type'), 'agent_logs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_logs_created_at'), 'agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_logs_related_order_id'), 'agent_logs', ['related_order_id'], unique=False)
    op.drop_index(op.f('idx_newspapers_order_id'), table_name='newspapers')
    op.drop_index(op.f('idx_newspapers_published_at'), table_name='newspapers')
    op.drop_index(op.f('idx_newspapers_scheduled_at'), table_name='newspapers')
    op.drop_index(op.f('idx_newspapers_status'), table_name='newspapers')
    op.drop_constraint(op.f('uq_newspaper_order_episode'), 'newspapers', type_='unique')
    op.create_index(op.f('ix_newspapers_order_id'), 'newspapers', ['order_id'], unique=False)
    op.create_index(op.f('ix_newspapers_scheduled_at'), 'newspapers', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_newspapers_status'), 'newspapers', ['status'], unique=False)
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_id'), table_name='orders')
    op.create_index(op.f('ix_orders_assigned_writer_id'), 'orders', ['assigned_writer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_index(op.f('idx_pub_schedules_scheduled_at'), table_name='publication_schedules')
    op.drop_index(op.f('idx_pub_schedules_status'), table_name='publication_schedules')
    op.drop_constraint(op.f('uq_schedule_order_episode'), 'publication_schedules', type_='unique')
    op.create_index(op.f('ix_publication_schedules_scheduled_at'), 'publication_schedules', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_publication_schedules_status'), 'publication_schedules', ['status'], unique=False)
    op.drop_index(op.f('idx_sponsor_slots_slot_type'), table_name='sponsor_slots')
    op.drop_index(op.f('idx_sponsor_slots_sponsor_id'), table_name='sponsor_slots')
    op.create_index(op.f('ix_sponsor_slots_slot_type'), 'sponsor_slots', ['slot_type'], unique=False)
    op.create_index(op.f('ix_sponsor_slots_sponsor_id'), 'sponsor_slots', ['sponsor_id'], unique=False)
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'organization_id')
    op.drop_index(op.f('ix_sponsor_slots_sponsor_id'), table_name='sponsor_slots')
    op.drop_index(op.f('ix_sponsor_slots_slot_type'), table_name='sponsor_slots')
    op.create_index(op.f('idx_sponsor_slots_sponsor_id'), 'sponsor_slots', ['sponsor_id'], unique=False)
    op.create_index(op.f('idx_sponsor_slots_slot_type'), 'sponsor_slots', ['slot_type'], unique=False)
    op.drop_index(op.f('ix_publication_schedules_status'), table_name='publication_schedules')
    op.drop_index(op.f('ix_publication_schedules_scheduled_at'), table_name='publication_schedules')
    op.create_unique_constraint(op.f('uq_schedule_order_episode'), 'publication_schedules', ['order_id', 'episode_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pub_schedules_status'), 'publication_schedules', ['status'], unique=False)
    op.create_index(op.f('idx_pub_schedules_scheduled_at'), 'publication_schedules', ['scheduled_at'], unique=False)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_assigned_writer_id'), table_name='orders')
    op.create_index(op.f('idx_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.drop_index(op.f('ix_newspapers_status'), table_name='newspapers')
    op.drop_index(op.f('ix_newspapers_scheduled_at'), table_name='newspapers')
    op.drop_index(op.f('ix_newspapers_order_id'), table_name='newspapers')
    op.create_unique_constraint(op.f('uq_newspaper_order_episode'), 'newspapers', ['order_id', 'episode_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_newspapers_status'), 'newspapers', ['status'], unique=False)
    op.create_index(op.f('idx_newspapers_scheduled_at'), 'newspapers', ['scheduled_at'], unique=False)
    op.create_index(op.f('idx_newspapers_published_at'), 'newspapers', ['published_at'], unique=False)
    op.create_index(op.f('idx_newspapers_order_id'), 'newspapers', ['order_id'], unique=False)
    op.drop_index(op.f('ix_agent_logs_related_order_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_created_at'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_type'), table_name='agent_logs')
    op.create_index(op.f('idx_agent_logs_order_id'), 'agent_logs', ['related_order_id'], unique=False)
    op.create_index(op.f('idx_agent_logs_created_at'), 'agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_agent_logs_agent_type'), 'agent_logs', ['agent_type'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
