"""add_payment_fields_to_orders

Revision ID: cc7f1eba4008
Revises: cd56ace7cdec
Create Date: 2026-03-06 07:34:31.193816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7f1eba4008'
down_revision: Union[str, None] = 'cd56ace7cdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_items_collection_name'), table_name='vector_items')
    op.drop_index(op.f('ix_vector_items_external_id'), table_name='vector_items')
    op.drop_table('vector_items')
    op.alter_column('agent_logs', 'input_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agent_logs', 'output_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.execute("ALTER TABLE newspapers ADD COLUMN IF NOT EXISTS sns_copy JSON;")
    op.execute("ALTER TABLE newspapers ADD COLUMN IF NOT EXISTS visual_prompt TEXT;")
    # orders 테이블 결제 추적 컬럼 추가 (IF NOT EXISTS - 중복 안전)
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS merchant_uid VARCHAR(100);")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS imp_uid VARCHAR(100);")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);")
    op.execute("""
        DO $$ BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_orders_merchant_uid') THEN
            ALTER TABLE orders ADD CONSTRAINT uq_orders_merchant_uid UNIQUE (merchant_uid);
          END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_orders_imp_uid') THEN
            ALTER TABLE orders ADD CONSTRAINT uq_orders_imp_uid UNIQUE (imp_uid);
          END IF;
        END $$;
    """)
    op.alter_column('newspapers', 'sidebar_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('newspapers', 'variables_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('orders', 'supporting_people',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'supporting_people',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('notifications', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('newspapers', 'variables_used',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('newspapers', 'sidebar_content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('uq_orders_imp_uid', 'orders', type_='unique')
    op.drop_constraint('uq_orders_merchant_uid', 'orders', type_='unique')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'imp_uid')
    op.drop_column('orders', 'merchant_uid')
    op.drop_column('newspapers', 'visual_prompt')
    op.drop_column('newspapers', 'sns_copy')
    op.alter_column('agent_logs', 'output_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_logs', 'input_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('vector_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_items_pkey'))
    )
    op.create_index(op.f('ix_vector_items_external_id'), 'vector_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_vector_items_collection_name'), 'vector_items', ['collection_name'], unique=False)
    # ### end Alembic commands ###
